### ISSUE TITLE
可以外接显示器吗

### ISSUE THREAD

**Issue by beyond-infra** [yaza-putu/lenovo-thinkpad-l430#1]
可以外接显示器吗？cpu能不能用i7？

**Comment by yaza-putu** [comment]
I can use external monitor with display port (DP)..
Vga port can't support by hackintosh fo r processor gen 3 (opencore).

You can read spesification my laptop in github..

For core i7 i thinking you need more read documentation dortonia opencore
for adjuts your settings ..

Thank you

Pada tanggal Sen, 28 Jun 2021 15.16, lilocon ***@***.***>
menulis:

**Comment by beyond-infra** [comment]
@yaza-putu   谢谢
